### ISSUE TITLE
[Bug]: Incompatibility with KubeJS, adjusting recipe has no effect

### ISSUE THREAD

**Issue by plantiac** [ixDarkLorD/CoolCatLib#1]
### Describe the Bug

Adjusting a recipe, e.g. replacing input has no effect

### To Reproduce

**Installed mods:**

Fabric - 0.15.6
architectury-6.5.85-fabric.jar
cloth-config-8.3.115-fabric.jar
coolcat_lib-fabric-1.19.2-v1.0.3-release.jar
fabric-api-0.77.0+1.19.2.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
inmis-2.7.1-1.19.jar
kubejs-fabric-1902.6.2-build.59.jar
rhino-fabric-1902.2.3-build.284.jar
RoughlyEnoughItems-9.1.682-fabric.jar

**KubeJS server script:**

`ServerEvents.recipes(event => {
    event.replaceInput(
        {output: 'inmis:frayed_backpack'},
        'minecraft:chest',
        'inmis:baby_backpack'
    )
})`

### Catch the bug In Action!

CoolCatLib disabled:

![Screenshot 2024-02-17 185245](https://github.com/ixDarkLorD/CoolCatLib/assets/104493176/97154da4-c0a7-4a65-ad6f-fe8829411754)

CoolCatLib enabled:

![Screenshot 2024-02-17 185021](https://github.com/ixDarkLorD/CoolCatLib/assets/104493176/6588fe47-dd6d-4965-8698-54881f2ff754)

### Crash Report or Log

https://gist.github.com/plantiac/87f7c33d8770d4e913cdb10421cd0fae

### OS

Windows 11

### Minecraft Version

1.19.2

### ModLoader

Fabric

### Mod Version

coolcat_lib-fabric-1.19.2-v1.0.3-release.jar

**Comment by ixDarkLorD** [comment]
I will look into it.

**Comment by ixDarkLorD** [comment]
Check out the new update
